/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Kantin;
import Entity.Menu;
import Koneksi.*;
import java.sql.*;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import sayapesan.Login;


/**
 *
 * @author Cerberus
 */
public class InputMenu extends javax.swing.JFrame {
    int value;
    int idmenu;
    String a,b,c;
    MenuCon menu = new MenuCon();
    List<Menu> data=new ArrayList<>();
        
    public InputMenu(int value){
       initComponents();
       this.value=value;
       load_table();
    }
 
    
    private void load_table(){
        //hapusIsiTable();
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Id Menu");
        model.addColumn("Nama Menu");
        model.addColumn("Harga Menu");
        model.addColumn("Jenis Menu");
        tabelmenu.setModel(model);
 
        data = menu.showData(value);
        for (int i = 0; i < data.size(); i++) {
            Object[] ob = new Object[4];
            ob[0] = data.get(i).getidmenu();
            ob[1] = data.get(i).getNamaMenu();
            ob[2] = data.get(i).getHargaMenu();
            ob[3] = data.get(i).getJenisMenu();
            model.addRow(ob);
        }   
    }
    
    
    private void hapus(){
        namamenu.setText(null);
        hargamenu.setText(null);
        jenismenu.setSelectedItem(this);
      
    }
    
    public InputMenu() {
        initComponents();  
        load_table();
        hapus();
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        namamenu = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        hargamenu = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jenismenu = new javax.swing.JComboBox<>();
        addBut = new javax.swing.JButton();
        editBut = new javax.swing.JButton();
        deleteBut = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelmenu = new javax.swing.JTable();
        Back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Input Menu");

        jLabel1.setText("Nama Menu");

        jLabel2.setText("Harga Menu");

        hargamenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hargamenuActionPerformed(evt);
            }
        });

        jLabel3.setText("Jenis Menu");

        jenismenu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Choose--", "Makanan", "Minuman" }));

        addBut.setText("Add");
        addBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButActionPerformed(evt);
            }
        });

        editBut.setText("Update");
        editBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButActionPerformed(evt);
            }
        });

        deleteBut.setText("Delete");
        deleteBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButActionPerformed(evt);
            }
        });

        tabelmenu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelmenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelmenuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelmenu);

        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jenismenu, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(namamenu)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(addBut, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(editBut, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(deleteBut))
                            .addComponent(hargamenu))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Back)))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(namamenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hargamenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jenismenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addBut)
                    .addComponent(editBut)
                    .addComponent(deleteBut))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Back)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        new KantinMenu(value).setVisible(true);
        dispose();
    }//GEN-LAST:event_BackActionPerformed

    private void addButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButActionPerformed
        // TODO add your handling code here:
        String nama = namamenu.getText();
        String price = hargamenu.getText();
        int harga = Integer.parseInt(price);
        String jenis = jenismenu.getSelectedItem().toString();
        
        if(nama.isEmpty() || price.isEmpty() || jenismenu.getSelectedItem().equals("--Choose--")){
            JOptionPane.showMessageDialog(null,"Isi Semua");
        }else{
            menu.setNamaMenu(nama);
            menu.setHargaMenu(harga);
            menu.setJenisMenu(jenis);
            menu.addData(value);
            JOptionPane.showMessageDialog(null,"Save Data Succes");
            new InputMenu(value).setVisible(true);
            hapus();
            this.dispose();
            
            
        }
        
        
    }//GEN-LAST:event_addButActionPerformed

    private void editButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButActionPerformed
        // TODO add your handling code here:
   
        menu.setNamaMenu(namamenu.getText());
        menu.setHargaMenu(Integer.parseInt(hargamenu.getText()));
        menu.setJenisMenu(jenismenu.getSelectedItem().toString());
        menu.updateData(idmenu);
        hapus();
        JOptionPane.showMessageDialog(null, "Update Data Succes");
        new InputMenu(value).setVisible(true);
        this.dispose();

    }//GEN-LAST:event_editButActionPerformed

    private void deleteButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButActionPerformed
        // TODO add your handling code here:
    int YesNo = JOptionPane.showConfirmDialog(null,"Anda yakin akan menghapus menu?","Delete Menu",JOptionPane.YES_NO_OPTION);
    if(YesNo == 0){
        menu.deleteData(idmenu);
        hapus();
        JOptionPane.showMessageDialog(null, "Delete Data Succes");
        new InputMenu(value).setVisible(true);
        this.dispose();
    } else{
        JOptionPane.showMessageDialog(null, "Delete failed");
        }  
   
    }//GEN-LAST:event_deleteButActionPerformed

    private void hargamenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hargamenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hargamenuActionPerformed

    private void tabelmenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelmenuMouseClicked
        // TODO add your handling code here:
        int index = tabelmenu.getSelectedRow();
        TableModel model = tabelmenu.getModel();
        idmenu = Integer.parseInt(model.getValueAt(index, 0).toString());
        a = model.getValueAt(index, 1).toString();
        namamenu.setText(a);
        b = model.getValueAt(index, 2).toString();
        hargamenu.setText(b);
        c = model.getValueAt(index, 3).toString();
        jenismenu.setSelectedItem(c);
    }//GEN-LAST:event_tabelmenuMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InputMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InputMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InputMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InputMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InputMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JButton addBut;
    private javax.swing.JButton deleteBut;
    private javax.swing.JButton editBut;
    private javax.swing.JTextField hargamenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jenismenu;
    private javax.swing.JTextField namamenu;
    private javax.swing.JTable tabelmenu;
    // End of variables declaration//GEN-END:variables
}
