/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Kantin;
import Koneksi.*;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Cerberus
 */
public class InputMenu extends javax.swing.JFrame {
    String sql;
    Connection con = null;
    PreparedStatement pst = null;
    ResultSet res = null;
    Statement stmt = null;
    /**
     * Creates new form InputMenu
     */
    
    private void load_table(String query){
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Id Menu");
        model.addColumn("Nama Menu");
        model.addColumn("Harga Menu");
        model.addColumn("Jenis Menu");
        
        try{
             //sql = "SELECT * FROM menu";
             stmt = con.createStatement();
             res = stmt.executeQuery(query);
             while(res.next()){
                 model.addRow(new Object[]{res.getString(1),res.getString(2),res.getString(3),res.getString(4)});
             }
             tabelmenu.setModel(model);
        } catch(Exception e){
            
        } 
        
        
    }
    
    private void hapus(){
        namamenu.setText(null);
        hargamenu.setText(null);
        jenismenu.setSelectedItem(this);
        cariform.setText(null);
    }
    
    public InputMenu() {
        initComponents();
        config DB = new config();
        DB.config();
        con = DB.con;
        load_table("SELECT * FROM menu");
        hapus();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        namamenu = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        hargamenu = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jenismenu = new javax.swing.JComboBox<>();
        addBut = new javax.swing.JButton();
        editBut = new javax.swing.JButton();
        deleteBut = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelmenu = new javax.swing.JTable();
        cariform = new javax.swing.JTextField();
        searchbut = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        Back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nama Menu");

        jLabel2.setText("Harga Menu");

        jLabel3.setText("Jenis Menu");

        jenismenu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Choose--", "Makanan", "Minuman" }));

        addBut.setText("Add");
        addBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButActionPerformed(evt);
            }
        });

        editBut.setText("Update");
        editBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButActionPerformed(evt);
            }
        });

        deleteBut.setText("Delete");
        deleteBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButActionPerformed(evt);
            }
        });

        tabelmenu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelmenu);

        searchbut.setText("Search");
        searchbut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbutActionPerformed(evt);
            }
        });

        jLabel4.setText("Cari Menu");

        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(searchbut)
                                .addGap(150, 150, 150))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(cariform)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel1)
                                        .addComponent(jenismenu, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(namamenu)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(addBut, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(editBut, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(deleteBut))
                                        .addComponent(hargamenu)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Back)))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(namamenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hargamenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jenismenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addBut)
                    .addComponent(editBut)
                    .addComponent(deleteBut))
                .addGap(10, 10, 10)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cariform, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchbut)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Back)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        new KantinMenu().setVisible(true);
        dispose();
    }//GEN-LAST:event_BackActionPerformed

    private void addButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButActionPerformed
        // TODO add your handling code here:
        String nama = namamenu.getText();
        String price = hargamenu.getText();
        double harga = Double.parseDouble(price);
        String jenis = jenismenu.getSelectedItem().toString();
        
        try{
            sql = "INSERT INTO menu (nama_menu, harga_menu, jenis) VALUES ('"+nama+"','"+harga+"','"+jenis+"')";
            if(nama.isEmpty()|| price.isEmpty()|| jenismenu.getSelectedItem()=="--Choose--"){
                JOptionPane.showMessageDialog(null,"Field harus di isi semua");
                load_table("SELECT * FROM menu");
            } else{
                pst=con.prepareStatement(sql);
                pst.execute();
                JOptionPane.showMessageDialog(null,"Penyimpanan Data Berhasil");
                load_table("SELECT * FROM menu");
                hapus();
            }
            
        } catch (Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        
    }//GEN-LAST:event_addButActionPerformed

    private void searchbutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbutActionPerformed
        // TODO add your handling code here:
        String search = cariform.getText();
        double cari = Double.parseDouble(search);
        try{        
            load_table("SELECT * FROM menu WHERE idMenu=('"+cari+"')");
            sql = "SELECT * FROM menu WHERE idMenu=('"+cari+"')";
            stmt = con.createStatement();
            res = stmt.executeQuery(sql);
            while(res.next()){
                namamenu.setText(res.getString("nama_menu"));
                hargamenu.setText(res.getString("harga_menu"));
                jenismenu.setName(res.getString("jenis"));
            }
         } catch (Exception e){
            
        }
    }//GEN-LAST:event_searchbutActionPerformed

    private void editButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButActionPerformed
        // TODO add your handling code here:
        String nama = namamenu.getText();
        String price = hargamenu.getText();
        int harga = Integer.parseInt(price);
        String jenis = jenismenu.getSelectedItem().toString();
        String search = cariform.getText();
        int cari = Integer.parseInt(search);
        try{
             sql = "UPDATE menu SET "
                   
                     + "nama_menu='"+nama+"',"
                     + "harga_menu="+harga+""
                    //+ "jenis"='"+jenis+"',"
                     + " where "
                     + "idmenu="+cari+";"; 
            // System.out.println(sql);
             pst=con.prepareStatement(sql);
             pst.execute();
             JOptionPane.showMessageDialog(null,"Update Data Berhasil");
             load_table("SELECT * FROM menu");
             hapus();
       
        } catch (Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        
        /*
        System.out.println("\n "+nama
                + "\n "+harga
                + "\n"+jenis);
        */
    }//GEN-LAST:event_editButActionPerformed

    private void deleteButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButActionPerformed
        // TODO add your handling code here:
        String search = cariform.getText();
        int cari = Integer.parseInt(search);
        try{
            sql = "DELETE FROM menu WHERE "
                    + "idmenu="+cari+";";
            pst = con.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null,"Hapus Data Berhasil");
            load_table("SELECT * FROM menu");
            hapus();
        }catch (Exception e){
            
        }
        
        
    }//GEN-LAST:event_deleteButActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InputMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InputMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InputMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InputMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InputMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JButton addBut;
    private javax.swing.JTextField cariform;
    private javax.swing.JButton deleteBut;
    private javax.swing.JButton editBut;
    private javax.swing.JTextField hargamenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jenismenu;
    private javax.swing.JTextField namamenu;
    private javax.swing.JButton searchbut;
    private javax.swing.JTable tabelmenu;
    // End of variables declaration//GEN-END:variables
}
