/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pemesan;

import Entity.Menu;
import Kantin.PemesanMenu;
import Koneksi.PemesananCon;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Cerberus
 */
public class LihatPesanan extends javax.swing.JFrame {
        PemesananCon menu = new PemesananCon();
        List<Menu> dataOrder=new ArrayList<>(); 
        PemesananCon orderPemesan = new PemesananCon();
        List<Menu> dataPemesan=new ArrayList<>();
        PemesananCon tagihPemesan = new PemesananCon();
        List<Menu> TagihanPemesan=new ArrayList<>();
        int value;
    /**
     * Creates new form LihatPesanan
     */
     
    private void load_tablePesanan(){
        DefaultTableModel modelPesan = new DefaultTableModel();
        modelPesan.addColumn("IdOrder");
        modelPesan.addColumn("Id");
        modelPesan.addColumn("Nama Menu");
        modelPesan.addColumn("Harga Menu");
        modelPesan.addColumn("Jenis Menu");
        modelPesan.addColumn("Nama Kantin");
        modelPesan.addColumn("id Kantin");
        dataPesanan.setModel(modelPesan);
        dataPesanan.removeColumn(dataPesanan.getColumnModel().getColumn(0));
        dataPesanan.removeColumn(dataPesanan.getColumnModel().getColumn(5));
        dataOrder.clear();
        dataOrder = menu.showDataOrder(value);
        for (int i = 0; i < dataOrder.size(); i++) {
            Object[] ob = new Object[7];
            ob[0] = dataOrder.get(i).O.getidOrder();
            ob[1] = dataOrder.get(i).getidmenu();
            ob[2] = dataOrder.get(i).getNamaMenu();
            ob[3] = dataOrder.get(i).getHargaMenu();
            ob[4] = dataOrder.get(i).getJenisMenu();
            ob[5] = dataOrder.get(i).t.getNamaTenant();
            ob[6] = dataOrder.get(i).t.getidTenant();
            modelPesan.addRow(ob);
        }
    }
    private void load_dataPemesan(){
         dataPemesan = orderPemesan.showDataPemesan(value);
         TagihanPemesan = tagihPemesan.HitungTagihan(value);
         idpemesan.setText(String.valueOf(dataPemesan.get(0).p.getIdpemesan()));
         namapemesan.setText(dataPemesan.get(0).p.getNama());
        alamat.setText("Lantai "+dataPemesan.get(0).p.getLantai()+"\n"
                + " Ruang "+dataPemesan.get(0).p.getRuang());
        Tagihan.setText(String.valueOf(TagihanPemesan.get(0).p.getTagihan()));
        
    }
    public LihatPesanan() {
        initComponents();
    }
    public LihatPesanan(int value) {
        initComponents();
        this.value= value;
        load_tablePesanan();
        load_dataPemesan();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        dataPesanan = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Tagihan = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        idpemesan = new javax.swing.JLabel();
        namapemesan = new javax.swing.JLabel();
        alamat = new javax.swing.JLabel();
        backBut = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Lihat Pesanan");

        dataPesanan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(dataPesanan);

        jLabel1.setText("Tagihan :");

        jLabel2.setText("Rp. ");

        Tagihan.setText("1200");

        jLabel3.setText("Nama Pemesan :");

        jLabel4.setText("Alamat Ruang   :");

        jLabel5.setText("ID Pemesan      :");

        idpemesan.setText("IdPemesan");

        namapemesan.setText("namaPemesan");

        alamat.setText("Alamat");

        backBut.setText("Back");
        backBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(alamat))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(backBut)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(namapemesan))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(idpemesan)
                                .addGap(67, 67, 67)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Tagihan)))))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backBut)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(idpemesan)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(Tagihan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(namapemesan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(alamat))
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButActionPerformed
        // TODO add your handling code here:
        new PemesanMenu(value).setVisible(true);
        dispose();
    }//GEN-LAST:event_backButActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LihatPesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LihatPesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LihatPesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LihatPesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LihatPesanan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Tagihan;
    private javax.swing.JLabel alamat;
    private javax.swing.JButton backBut;
    private javax.swing.JTable dataPesanan;
    private javax.swing.JLabel idpemesan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel namapemesan;
    // End of variables declaration//GEN-END:variables
}
