/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pemesan;

import Entity.Menu;
import Kantin.PemesanMenu;
import Koneksi.PemesananCon;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Cerberus
 */
public class LihatMenu extends javax.swing.JFrame {
    PemesananCon menu = new PemesananCon();
    List<Menu> data=new ArrayList<>();
    List<Menu> dataOrder=new ArrayList<>();        

    
    int value;
    /**
     * Creates new form LihatMenu
     */
    public LihatMenu() {
        initComponents();
        load_table();
        load_tablePesanan();
    }
    public LihatMenu(int value) {
        initComponents();
        this.value = value;
        load_table();
        load_tablePesanan();
        setLocationRelativeTo(null);  
    }
    private void load_table(){
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("IdOrder");
        model.addColumn("Id");
        model.addColumn("Nama Menu");
        model.addColumn("Harga Menu");
        model.addColumn("Jenis Menu");
        model.addColumn("Nama Kantin");
        model.addColumn("id Kantin");
        TableMenu.setModel(model);
        TableMenu.removeColumn(TableMenu.getColumnModel().getColumn(0));
        TableMenu.removeColumn(TableMenu.getColumnModel().getColumn(5));
 
        data = menu.showDataMenu();
        for (int i = 0; i < data.size(); i++) {
            Object[] ob = new Object[7];
            ob[1] = data.get(i).getidmenu();
            ob[2] = data.get(i).getNamaMenu();
            ob[3] = data.get(i).getHargaMenu();
            ob[4] = data.get(i).getJenisMenu();
            ob[5] = data.get(i).t.getNamaTenant();
            ob[6] = data.get(i).t.getidTenant();
            model.addRow(ob);
        }   
    }
    private void clear_tablePesanan(){
        TabelPesan.setModel(new DefaultTableModel(null, new String[] {"Id","Nama Menu","Harga Menu","Jenis Menu","Nama Kantin"} ));
    }
    private void load_tablePesanan(){
        DefaultTableModel modelPesan = new DefaultTableModel();
        modelPesan.addColumn("IdOrder");
        modelPesan.addColumn("Id");
        modelPesan.addColumn("Nama Menu");
        modelPesan.addColumn("Harga Menu");
        modelPesan.addColumn("Jenis Menu");
        modelPesan.addColumn("Nama Kantin");
        modelPesan.addColumn("id Kantin");
        TabelPesan.setModel(modelPesan);
        TabelPesan.removeColumn(TabelPesan.getColumnModel().getColumn(0));
        TabelPesan.removeColumn(TabelPesan.getColumnModel().getColumn(5));
        dataOrder.clear();
        dataOrder = menu.showDataOrder(value);
        for (int i = 0; i < dataOrder.size(); i++) {
            Object[] ob = new Object[7];
            ob[0] = dataOrder.get(i).O.getidOrder();
            ob[1] = dataOrder.get(i).getidmenu();
            ob[2] = dataOrder.get(i).getNamaMenu();
            ob[3] = dataOrder.get(i).getHargaMenu();
            ob[4] = dataOrder.get(i).getJenisMenu();
            ob[5] = dataOrder.get(i).t.getNamaTenant();
            ob[6] = dataOrder.get(i).t.getidTenant();
            modelPesan.addRow(ob);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinner1 = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableMenu = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        TabelPesan = new javax.swing.JTable();
        TambahBut = new javax.swing.JButton();
        HapusBut = new javax.swing.JButton();
        PesanBut = new javax.swing.JButton();
        CancelBut = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Daftar Menu");

        TableMenu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "null", "Id", "Nama Menu", "Harga Menu", "Jeni Menu", "Nama Kantin", "Title 7"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TableMenu);
        if (TableMenu.getColumnModel().getColumnCount() > 0) {
            TableMenu.getColumnModel().getColumn(4).setResizable(false);
        }

        TabelPesan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(TabelPesan);

        TambahBut.setText("Tambah >>");
        TambahBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TambahButActionPerformed(evt);
            }
        });

        HapusBut.setText("<< Hapus");
        HapusBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HapusButActionPerformed(evt);
            }
        });

        PesanBut.setText("Pesan");
        PesanBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PesanButActionPerformed(evt);
            }
        });

        CancelBut.setText("Cancel");
        CancelBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PesanBut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TambahBut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(HapusBut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CancelBut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(TambahBut)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(HapusBut)
                        .addGap(34, 34, 34)
                        .addComponent(PesanBut, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CancelBut)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TambahButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TambahButActionPerformed
        // TODO add your handling code here:
        TableModel model1 = TableMenu.getModel();
        int[] index = TableMenu.getSelectedRows();
        Object[] row = new Object[7];
        DefaultTableModel model2 = (DefaultTableModel) TabelPesan.getModel();
        for (int i = 0; i < index.length; i++) {
            row[0] = model1.getValueAt(index[i], 0);
            row[1] = model1.getValueAt(index[i], 1);
            row[2] = model1.getValueAt(index[i], 2);
            row[3] = model1.getValueAt(index[i], 3);
            row[4] = model1.getValueAt(index[i], 4);
            row[5] = model1.getValueAt(index[i], 5);
            row[6] = model1.getValueAt(index[i], 6);
            menu.addDataOrder(value,(Integer) row[1], (Integer) row[6]);
            //clear_tablePesanan();
            load_tablePesanan();
             model2.addRow(row);
        }
    }//GEN-LAST:event_TambahButActionPerformed

    private void HapusButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HapusButActionPerformed
        // TODO add your handling code here:
        TableModel getModelRemove = TabelPesan.getModel();
        int[] index = TabelPesan.getSelectedRows();
        DefaultTableModel modelRemove = (DefaultTableModel) TabelPesan.getModel();
        int remove = TabelPesan.getSelectedRow();
        Object[] row = new Object[7];
        if(remove >= 0 ){
        for (int i = 0; i < index.length; i++) {
            row[0] = getModelRemove.getValueAt(index[i], 0);
            System.out.println((Integer) row[0]);
            menu.deleteData((Integer) row[0]);
            modelRemove.removeRow(remove);
        }
        }else{
            JOptionPane.showMessageDialog(null,"Pilih salah satu menu yang akan dihapus");
        }
    }//GEN-LAST:event_HapusButActionPerformed

    private void CancelButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButActionPerformed
        // TODO add your handling code here:
        new PemesanMenu(value).setVisible(true);
        dispose();
    }//GEN-LAST:event_CancelButActionPerformed

    private void PesanButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PesanButActionPerformed
        // TODO add your handling code here:
     if(TabelPesan.getModel().getRowCount()==0){
        JOptionPane.showMessageDialog(null,"Mohon tambahkan menu terlebih dahulu"); 
     }else{
        JOptionPane.showMessageDialog(null,"Terima Kasih atas pesanannya!!");
        new PemesanMenu(value).setVisible(true);
        dispose();
        }
    }//GEN-LAST:event_PesanButActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LihatMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LihatMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LihatMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LihatMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LihatMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelBut;
    private javax.swing.JButton HapusBut;
    private javax.swing.JButton PesanBut;
    private javax.swing.JTable TabelPesan;
    private javax.swing.JTable TableMenu;
    private javax.swing.JButton TambahBut;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jSpinner1;
    // End of variables declaration//GEN-END:variables
}
